backend:
  name: github
  repo: Web-Point/blog

media_folder: static/assets
public_folder: assets

collections:
  - name: post
    label: Post
    folder: posts
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      # - {label: Featured Image, name: thumbnail, widget: image}
      - { name: path, label: Path }
      - { name: Publish Date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }

